language: ruby
rvm:
  - 2.3.0
bundler_args: --without production
script:
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake
before_script:
  - psql -c 'create database sm_test;' -U postgres
sudo: false
