smtp_settings:
  address: smtp.yandex.ru
  port: 465
  domain: skymemories.ru
  authentication: plain
  user_name: info@skymemories.ru
  password: <%= ENV['MAIL_PASSWORD'] %>
  enable_starttls_auto: true
  ssl: true
