development:
  adapter: postgresql
  host: localhost
  database: sm_dev
  username: sm_dev
  password: qwerty
  encoding: unicode
  reconnect: false
  pool: 5

test: &test
  adapter: postgresql
  host: localhost
  database: sm_test
  username: sm_test
  password: qwerty
  encoding: unicode
  reconnect: false
  pool: 5

production:
  adapter: postgresql
  host: localhost
  database: sm_prod
  username: sm_prod
  password: <%= ENV['SM_DB_PASSWORD'] %>
  encoding: unicode
  reconnect: false
  pool: 5

cucumber:
  <<: *test