connection: &connection
  adapter: postgresql
  encoding: unicode
  host: localhost
  reconnect: false
  pool: 5

development:
  <<: *connection
  database: sm_dev
  username: postgres

test: &test
  <<: *connection
  database: sm_test
  username: postgres

production:
  <<: *connection
  database: sm_prod
  username: sm_prod
  password: <%= ENV['SM_DB_PASSWORD'] %>

cucumber:
  <<: *test